name: Lambda CICD

on:
  push:
    branches:
      - main
    paths:
      - 'lambda/'

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python     #setup python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'
      
      - name: Install dependencies #install dependencies if any
        run: |
          python -m pip install --upgrade pip
          pip install -r lambda/requirements.txt -t lambda/
      
      - name: Configure AWS credentials #configure secrets
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-south-1
        
      - name: Deploy to AWS lambda  #deploying function to aws lambda
        run: |
          cd lambda
          zip -r lambda.zip
          aws lambda update-function-code --function-name lambda-functioncicd --zip-file fileb://lambda.zip